<?php

/*
 * HiDev config for HiSite
 *
 * @link      https://github.com/hiqdev/hidev-hisite
 * @package   hidev-hisite
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2016, HiQDev (http://hiqdev.com/)
 */

namespace hidev\hisite\tests\unit\controllers;

use hidev\hisite\controllers\HiSiteController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-14 at 11:42:17.
 */
class HiSiteControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HiSiteController
     */
    protected $object;
    protected $ip = '1.1.1.1';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HiSiteController('hisite', null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::getDomain
     * @todo   Implement testGetDomain().
     */
    public function testGetDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::getPrjDir
     * @todo   Implement testGetPrjDir().
     */
    public function testGetPrjDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::getWebDir
     * @todo   Implement testGetWebDir().
     */
    public function testGetWebDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::getLogDir
     * @todo   Implement testGetLogDir().
     */
    public function testGetLogDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    public function testGetIp()
    {
        $this->object->setIp($this->ip);
        $this->assertSame($this->ip, $this->object->getIp());
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::findIp
     * @todo   Implement testFindIp().
     */
    public function testFindIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::getFpmSocket
     * @todo   Implement testGetFpmSocket().
     */
    public function testGetFpmSocket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hidev\hisite\controllers\HiSiteController::findFpmSocketFile
     * @todo   Implement testFindFpmSocketFile().
     */
    public function testFindFpmSocketFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
