<?php

/*
 * HiDev config for HiSite
 *
 * @link      https://github.com/hiqdev/hidev-hisite
 * @package   hidev-hisite
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2016, HiQDev (http://hiqdev.com/)
 */

namespace hidev\hisite\tests\unit\controllers;

use hidev\hisite\controllers\HiSiteController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-14 at 11:42:17.
 */
class HiSiteControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HiSiteController
     */
    protected $object;
    protected $ip = '1.1.1.1';

    protected function setUp()
    {
        $this->object = new HiSiteController('test', null);
    }

    protected function tearDown()
    {
    }

    public function testConstruct()
    {
        $this->assertInstanceOf(HiSiteController::class, $this->object);
    }
}
