install:
    before:
        - hisite

nginx:
    before:
        - hisite

hisite:
    path:   .
    web:
        assets:
            chmod: '0777'
        index.php:
            once:     true
            template: hisite/web/index.twig
        robots.txt:
            once:     true
            template: hisite/web/robots.twig
    runtime:
        chmod:  '0777'
    src:
        config:
            defines.php:
                class:    hisite-defines
                template: hisite/config/defines.twig
            bootstrap.php:
                once:     true
                template: hisite/config/bootstrap.twig
            hidev.php:
                once:     true
                template: hisite/config/hidev.twig
            hisite.php:
                once:     true
                template: hisite/config/hisite.twig
            params.php:
                once:     true
                template: hisite/config/params.twig
            web.php:
                once:     true
                template: hisite/config/web.twig

